name: vodafone-chaostoolkit-locust
on:
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Download dependencies
        run: |
          python3 -m pip install -r requirements.txt;
          python3 -m pip install -r requirements-dev.txt
      - name: Static analysis
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Anti Virus Scan
        uses: djdefi/gitavscan@main
        with:
          full: '--full'
  build-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Download dependencies
        run: |
          python3 -m pip install -r requirements.txt;
          python3 -m pip install -r requirements-dev.txt
      - name: Build package
        run: |
          python3 setup.py bdist_wheel;
          python3 -m pip install dist/chaostoolkit_locust-0.0.1-py3-none-any.whl
      - name: Run unit test
        run: |
          pytest ./tests
